version: '3'

vars:
  DB_HOST: localhost
  DB_PORT: 5432
  DB_USER: user
  DB_PASSWORD: password
  DB_NAME: mydb
  MIGRATIONS_DIR: ./migrations
  Goose: goose

tasks:
  # Migration management tasks
  create-migration:
    desc: Create a new migration file
    cmds:
      - {{.Goose}} -dir {{.MIGRATIONS_DIR}} create {{.name}} sql
    vars:
      name:
        sh: echo "migration_$(date +%Y%m%d%H%M%S)"

  create-migration-up-down:
    desc: Create a new migration file with up and down functions
    cmds:
      - {{.Goose}} -dir {{.MIGRATIONS_DIR}} create -ext sql -seq {{.name}}
    vars:
      name:
        sh: echo "migration_$(date +%Y%m%d%H%M%S)"

  # Database connection tasks
  db-up:
    desc: Start the database using docker-compose
    cmds:
      - docker-compose up -d db

  db-down:
    desc: Stop the database
    cmds:
      - docker-compose down

  db-reset:
    desc: Reset the database (stop, remove volumes, start)
    cmds:
      - docker-compose down -v
      - docker-compose up -d db

  # Migration execution tasks
  migrate-up:
    desc: Run all pending migrations
    env:
      GOOSE_DBSTRING: postgres://{{.DB_USER}}:{{.DB_PASSWORD}}@{{.DB_HOST}}:{{.DB_PORT}}/{{.DB_NAME}}?sslmode=disable
    cmds:
      - {{.Goose}} -dir {{.MIGRATIONS_DIR}} up

  migrate-down:
    desc: Rollback the last migration
    env:
      GOOSE_DBSTRING: postgres://{{.DB_USER}}:{{.DB_PASSWORD}}@{{.DB_HOST}}:{{.DB_PORT}}/{{.DB_NAME}}?sslmode=disable
    cmds:
      - {{.Goose}} -dir {{.MIGRATIONS_DIR}} down

  migrate-reset:
    desc: Reset database to initial state
    env:
      GOOSE_DBSTRING: postgres://{{.DB_USER}}:{{.DB_PASSWORD}}@{{.DB_HOST}}:{{.DB_PORT}}/{{.DB_NAME}}?sslmode=disable
    cmds:
      - {{.Goose}} -dir {{.MIGRATIONS_DIR}} reset

  migrate-status:
    desc: Check migration status
    env:
      GOOSE_DBSTRING: postgres://{{.DB_USER}}:{{.DB_PASSWORD}}@{{.DB_HOST}}:{{.DB_PORT}}/{{.DB_NAME}}?sslmode=disable
    cmds:
      - {{.Goose}} -dir {{.MIGRATIONS_DIR}} status

  migrate-redo:
    desc: Rollback and re-run the last migration
    env:
      GOOSE_DBSTRING: postgres://{{.DB_USER}}:{{.DB_PASSWORD}}@{{.DB_HOST}}:{{.DB_PORT}}/{{.DB_NAME}}?sslmode=disable
    cmds:
      - {{.Goose}} -dir {{.MIGRATIONS_DIR}} redo

  # Complete workflow tasks
  setup-db:
    desc: Set up database and run migrations
    cmds:
      - task: db-up
      - task: migrate-up

  teardown-db:
    desc: Stop database and cleanup
    cmds:
      - task: db-down

  reset-db:
    desc: Reset database and rerun migrations
    cmds:
      - task: db-reset
      - task: migrate-up

  # Install goose if not present
  install-goose:
    desc: Install goose migration tool
    cmds:
      - go install github.com/pressly/goose/v3/cmd/goose@latest

  # Default task
  default:
    desc: Show help
    cmds:
      - task --list